# Controlador de estados
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Controladores para articulaciones
prismatic_joint_rail_position_controller:
  type: effort_controllers/JointPositionController
  joint: prismatic_joint_rail
  pid: {p: 3.0, i: 1.0, d: 1.0}

joint_1_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_1
  pid: {p: 200.0, i: 0.1, d: 30.0}

joint_2_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_2
  pid: {p: 200.0, i: 0.1, d: 30.0}

joint_3_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_3
  pid: {p: 200.0, i: 0.1, d: 30.0}

joint_4_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_4
  pid: {p: 100.0, i: 0.05, d: 20.0}

joint_5_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_5
  pid: {p: 80.0, i: 0.05, d: 15.0}

joint_6_position_controller:
  type: effort_controllers/JointPositionController
  joint: joint_6
  pid: {p: 60.0, i: 0.05, d: 10.0}
